name: 🐞 Bug or Error Report
description: Submit a bug or error report.
labels: ["type: something isn't working", "status: investigate"]

body:
- type: markdown
  attributes:
    value: |
      This issue type is for submitting bugs or errors you believe you have found with the PnPjs library. If your submission references permission errors or 5xx status code responses, this is almost certainly not a bug with PnPjs but rather and issue with your configuration, please refer to other support options listed on the [new issue chooser page](https://github.dev/juliemturner/pnpjs/issues/new/choose). Please provide as much information as possible so we can best address your submission. Thanks!

      - Follow our guidance on [How To Create Good Issues](https://github.dev/juliemturner/pnpjs/wiki/How-to-Create-Good-Issues).
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
- type: dropdown
  attributes:
    label: Major Version
    options:
      - 4.x
      - 3.x (No longer supported)
      - 2.x (No longer supported)
      - 1.x (No longer supported)
    default: 0
  validations:
    required: true
- type: input
  id: minorver
  attributes:
    label: Minor Version Number
    description: Include the minor and patch version numbers, e.g. for 4.1.0 
    placeholder: '1.0'
  validations:
    required: true
- type: dropdown
  attributes:
    label: Target environment
    options:
      - All
      - SharePoint Framework
      - NodeJS
      - Browser App (Hosted external to Microsoft 365 platform)
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional environment details
    description: Please describe the environment you're working in and how you're authenticating.
    placeholder: |
      I'm using NodeJS and certificate based MSAL for authentication.
  validations:
    required: true    
- type: textarea
  attributes:
    label: Expected or Desired Behavior
    description: Describe what you are trying to accomplish.
    placeholder: |
      I'm trying to get items from a list in a site.
  validations:
    required: true         
- type: textarea
  attributes:
    label: Observed Behavior
    description: Describe the results you're getting.
    placeholder: |
      I'm getting an empty response
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Please included code fenced example code, OR a link to a code snippet using GitHub or CodePen or the like to show how your code is structured. See the sample above.
    placeholder: |
      Here is the code I'm running
      
      ```TypeScript
      import { spfi } from "@pnp/sp";
      import "@pnp/sp/webs";
      import "@pnp/sp/lists";
      import "@pnp/sp/items";

      const sp = spfi(...);

      // get all the items from a list
      const items: any[] = await sp.web.lists.getByTitle("My List").items();
      console.log(items);
      ```  
  validations:
    required: true
